FROM ruby:2.7.1-alpine3.12

# declare APP alone to interpolate for other ENV vars
ARG APP=/app
ENV BUNDLER_VERSION="2.1.4" \
    # set as bundler defaults to ~/.bundle
    BUNDLE_HOME="$APP/.bundle" \
    # deployment implies --frozen true --path vendor/bundle
    BUNDLE_DEPLOYMENT="true" \
    # number of gems bundler can install in parallel (# of t2.xlarge vCPU - 1)
    BUNDLE_JOBS="3" \
    # set default locale as ruby defaults to US-ASCII
    LANG="C.UTF-8" \
    # add binstubs dir to path
    PATH="$APP/bin:$PATH"

ARG BUILD_PKGS='build-base curl git gnupg openssh-client zlib-dev'
# libc6-compat is needed since alpine linux uses musl libc instead of glibc. without libc6-compat
# the pdftohtml binary can't be found in PATH even though it lives in /usr/local/bin because
# pdftohtml is linked via glibc e.g. ldd /usr/local/bin/pdftohtml
ARG DEV_PKGS='bash file fontconfig libc6-compat libpng-dev postgresql-dev'
ARG APP_PKGS='imagemagick postgresql-client tzdata yarn'
# -U = update and upgrade
RUN apk -U upgrade \
      # --no-cache runs rm -rf /var/cache/apk/* after installation
      && apk add --no-cache $BUILD_PKGS $DEV_PKGS $APP_PKGS

# ensure binary is available for CircleCI
COPY ./pdftohtml /usr/local/bin/pdftohtml

# install and configure bundler for app and CI
RUN echo 'gem: --no-rdoc --no-ri' > ~/.gemrc \
      && gem install bundler -v "$BUNDLER_VERSION"

WORKDIR $APP
